### ISSUE TITLE
Additional option - remove "Log in or register to post comments"

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/views_system#2]
Hi!

I am not sure but may be you could add this option we talk about here https://github.com/backdrop/backdrop-issues/issues/1787

Thank you!

**Comment by klonos** [comment]
@bd0bd this module is totally unrelated to the content type display. This adds the ability to core Views to handle modules, themes and theme engines. You can use it for example to create your own version of the Modules page (`/admin/modules`) or the Themes page (`/admin/appearance`).
